using System.Collections;
using System.Collections.Generic;
using System.Linq;
using JunkStorm;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;


public struct RulebookSection
{
    public string Title;
    public string Content;

    public RulebookSection(string title, string content)
    {
        Title = title;
        Content = content;
    }
}

public sealed class JunkStormUnityController : MonoBehaviour
{
    [SerializeField] private Font uiFont;

    private JunkStormGame game;
    private const string DefaultInfoText = "Hover over a button for details.";

    private static readonly RulebookSection[] RulebookSections =
    {
        new RulebookSection("Overview", "Junk Storm is a competitive deckbuilding board game prototype for 2–4 local hot-seat players.\n\nPlayers are Influencers trying to lead survivors on a ruined Earth. Each generation, players send workers on expeditions, scavenge cards, play cards, build colony infrastructure, survive the Junk Storm and Biodomers, and race to complete a Tier 3 victory project.\n\nAll visuals are placeholders. The goal of this prototype is to test whether the core loop is fun."),
        new RulebookSection("Goal of the Game", "A player wins at the end of a generation if they have:\n\n- At least 10 Clout\n- At least one Tier 3 building\n\nIf multiple players win in the same generation:\n\n1. Highest Clout wins.\n2. If tied, the player with the most Tier 2 buildings wins.\n3. If still tied, the players share victory."),
        new RulebookSection("Key Resources", "Clout represents social influence, morale, leadership, and political power. Each player starts with 1 Clout. Clout determines how many worker tokens may go on expeditions and may also be spent during Action: spend 1 Clout to gain 1 worker token, or spend 1 Clout to add 1 Worker card to your Recycle Pile. Voluntary spending may reduce your Clout to 0 without eliminating you. Forced Clout loss that reduces you to 0 immediately eliminates you.\n\nWorker Tokens represent people who follow a player into danger. Each player starts with 3 worker tokens. They are sent on expeditions, may die to hazards, and surviving workers return during Reset.\n\nStored Resources are Alloy, Organics, and Plastoid. They are gained by playing Resource cards, persist between turns and generations, and are spent to build buildings.\n\nTemporary Labor is generated by Worker cards, required to build buildings, and resets to 0 during Reset."),
        new RulebookSection("Cards and Decks", "Each player has four card zones: Hand, Draw Pile, Recycle Pile, and Discard Pile. Recycled cards enter the Recycle Pile and can return when the Draw Pile is rebuilt. Discarded cards are permanently removed from the game and never reshuffled. Each starter deck contains 1 Dweller, 1 Worker, 1 Soldier, 1 Storm Shield, 1 Alloy, 1 Organics, and 1 Plastoid. Players draw 5 cards.\n\nIf a player must draw and their Draw Pile is empty, shuffle the Recycle Pile into a new Draw Pile.\n\nRecycle uses the recycle effect, then places the card in the Recycle Pile. Discard uses the discard effect, then removes the card from the game.\n\nStarter effects:\nDweller — Recycle: Gain 1 Clout. Discard: Gain 2 Clout.\nWorker — Recycle: Gain 1 temporary Labor. Discard: Gain 2 temporary Labor.\nSoldier — Recycle: Gain 1 Defense Strength. Discard: Cancel a Biodomer attack, attack another player at your Location, or defend against a Soldier attack.\nStorm Shield — Recycle: Draw 1 card. Discard: Cancel all Junk Storm effects against you.\nAlloy/Organics/Plastoid — Recycle: Gain 1 stored resource. Discard: Gain 2 stored resources."),
        new RulebookSection("Generation Structure", "First Player rotates each generation. Expedition and Action phases start with the First Player.\n\nEach generation has four phases:\n\n1. Expedition Phase\n2. Action Phase\n3. Junk Storm Phase\n4. Reset Phase\n\nDuring Expedition, players choose where to send worker tokens. During Action, players play cards and build buildings. During Junk Storm, either the Junk Storm or Biodomers move and resolve effects. During Reset, players return home, clean up temporary effects, draw back up to 5 cards, and check victory."),
        new RulebookSection("Expedition Phase", "In turn order, each player may choose a destination and send worker tokens up to current Clout, never more than they own. A player may also skip and send 0 worker tokens. Players may visit a valid Location, the Biodome if they meet requirements, or the Wilderness.\n\nPlayers cannot choose a Location with the Junk Storm or Biodomers; that Location is unsafe.\n\nClick a Location once to assign 1 worker. Click it again to assign another worker. Clicking a different Location switches destination and resets assigned workers to 1. Click Confirm Expedition to send assigned workers, Skip Expedition to send 0 workers, or Clear Expedition Selection to start over.\n\nLocation Expedition: draw 1 scavenge card from that Location deck per worker token sent. Event cards resolve immediately and are discarded. Non-event cards go to Recycle Pile unless a bonus changes that.\n\nBiodome Expedition requires at least 5 Clout and 5 worker tokens. Lose 5 workers, lose 5 Clout as forced loss, and draw 1 Special card. If forced Clout loss reduces you to 0, you are eliminated.\n\nWilderness has no scavenge deck. You cannot be targeted by Attack cards or use Defense cards, but remain vulnerable to hazards."),
        new RulebookSection("Action Phase", "During your Action turn, you may recycle or discard cards from hand, generate stored resources, generate temporary Labor, spend 1 Clout to gain 1 worker token, spend 1 Clout to add 1 Worker card to your Recycle Pile, build up to one building, use available special actions, and end your turn. Voluntary Clout spending may reduce you to 0 without elimination. Players at the same Location may discard Soldier to attack; if undefended, the attacker steals 1 random card from the target hand if possible and the target loses 1 Clout as forced loss. The target or another player at that Location may discard Soldier to defend.\n\nA player may play any number of cards from hand. Each played card must be recycled or discarded. A player may build at most one building per generation. Stored resources persist. Temporary Labor resets during Reset."),
        new RulebookSection("Junk Storm Phase", "Roll 1d10. On 1–5, move the Junk Storm. On 6–10, move the Biodomers. Odd rolls move counterclockwise; even rolls move clockwise. Junk Storm moves spaces equal to the roll. Biodomers move spaces equal to the roll minus 5.\n\nJunk Storm movement is shown one Location at a time. The arrow indicates direction. Junk Storm affects every Location it passes over, including where it lands. Discard the top card of each affected Location deck. Players at affected Locations discard the top card of their deck, lose all expedition workers, and lose 1 Clout per worker lost. Storm Shield can cancel this.\n\nBiodomers movement is shown one Location at a time. Biodomers attack players where they land. An attacked player loses 2 worker tokens and 1 Clout per worker lost. Soldier or Weapon Outfitting can cancel this."),
        new RulebookSection("Reset Phase", "During Reset:\n\n- Each player may move remaining hand cards to the Recycle Pile.\n- Surviving expedition workers return.\n- Player tokens return to the Colony.\n- Temporary Labor resets to 0.\n- Stored resources remain.\n- Per-generation flags reset.\n- Each player draws back up to 5 cards.\n- Victory is checked.\n- First player rotates clockwise."),
                new RulebookSection("Locations", "The main play area uses three columns: generation and player info on the left, cards and actions in the center, and the Location board on the right.\n\nThe five main Locations are shown as pentagon-style buttons on the right-side board in movement-ring order. Each Location button shows its remaining card count, selected expedition worker count, and any [JUNK STORM] or [BIODOMERS] threat marker directly on the tile.\n\nDuring Expedition, click a Location tile to assign 1 worker, click the same tile again to assign another worker, then Confirm Expedition from the center panel when ready.\n\nCity Ruins contains a mix of Alloy, Organics, Plastoid, Attack cards, and Events. Suburbs contains Organics, Plastoid, Dweller-style cards, Passive cards, and Events. Research Facility contains Plastoid, Alloy, Passive cards, Defense cards, and Events. Military Base contains Alloy, Plastoid, Soldier cards, Weapon cards, Attack cards, and Events. Farmlands contains Organics, Worker cards, Passive cards, and Events.\n\nWilderness has no scavenge deck. Biodome contains Special cards."),
                new RulebookSection("Buildings", "Buildings are purchased from the Shop / Build window in the center Cards / Hand / Actions panel. Available buildings appear in the normal orange style; unavailable buildings are greyed out but remain hoverable and clickable for feedback. Hover over a Shop entry to see its cost, requirements, effect, and why it can or cannot currently be built.\n\nBuildings are constructed by spending stored resources and temporary Labor. Stored Alloy, Organics, and Plastoid persist between generations. Temporary Labor is generated by Worker cards and resets to 0 during Reset.\n\nTier 1 buildings are personal buildings; each player may build up to 4 and gains +2 Clout when building one. Tier 2 buildings require a matching Tier 1, another Tier 1, 6 Clout, 2 Labor, and stored resources. Tier 3 buildings require 10 Clout, the required Tier 2 building, 3 Labor, and stored resources.\n\nBuilding a Tier 3 building enables victory at the end of the generation."),
        new RulebookSection("Victory", "Victory is checked at the end of each generation. A player wins if they have at least 10 Clout and at least one Tier 3 building.\n\nIf more than one player qualifies, use these tiebreakers:\n\n1. Highest Clout\n2. Most Tier 2 buildings\n3. Shared victory"),
        new RulebookSection("Current Prototype Simplifications", "This is a prototype, not the final board game. Known simplifications may include random or simplified targeting, automated building bonuses, default-priority resource payments, Wilderness alternate victory not implemented, shared-location conflict not fully implemented, and placeholder visuals.\n\nThe purpose is to test the core loop: Expedition → Scavenge → Play Cards → Build → Survive → Reset.")
    };

    private Transform boardRoot;
    private Transform controlRoot;
    private Transform rightBoardRoot;
    private Transform logRoot;
    private Transform utilityRoot;
    private GameObject rulebookOverlay;
    private Text rulebookContentText;
    private Text infoBannerText;
    private bool inputLocked;
    private int? displayedJunkStormOutpost;
    private int? displayedBiodomerOutpost;
    private int selectedExpeditionOutpost = -1;
    private int assignedExpeditionWorkers;

    private void Awake()
    {
        EnsureEventSystem();
        game = new JunkStormGame();
        BuildCanvas();
        Render();
    }

    private void BuildCanvas()
    {
        var canvasObject = new GameObject("Junk Storm Canvas", typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster));
        var canvas = canvasObject.GetComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;

        var scaler = canvasObject.GetComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1600, 900);

        var root = CreateBackgroundPanel(canvasObject.transform, "Root", new Color(0.08f, 0.06f, 0.05f));
        Stretch(root.GetComponent<RectTransform>());

        var title = CreateText(root.transform, "Title", "Junk Storm", 48, FontStyle.Bold, Color.white);
        Anchor(title.rectTransform, new Vector2(0, 1), new Vector2(1, 1), new Vector2(32, -74), new Vector2(-32, -16));

        var infoBanner = CreateBackgroundPanel(root.transform, "Info Banner", new Color(0.16f, 0.11f, 0.07f));
        Anchor(infoBanner.GetComponent<RectTransform>(), new Vector2(0, 1), new Vector2(1, 1), new Vector2(32, -128), new Vector2(-32, -78));
        infoBannerText = CreateText(infoBanner.transform, "Info Text", DefaultInfoText, 20, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));
        Stretch(infoBannerText.rectTransform, 16, -8, -16, 8);

        utilityRoot = CreateUtilityPanel(root.transform).transform;
        Anchor((RectTransform)utilityRoot, new Vector2(1, 1), new Vector2(1, 1), new Vector2(-332, -74), new Vector2(-32, -16));
        CreateButton(utilityRoot, "Rulebook", ShowRulebook, true, "Rulebook — Open the indexed rules reference.");
        CreateButton(utilityRoot, "New Game", () =>
        {
            game.NewGame();
            ClearExpeditionSelectionState();
            Render();
            ClearInfo();
        }, true, "New Game — Restart the prototype from Generation 1.");

        BuildRulebookOverlay(root.transform);

        boardRoot = CreateScrollablePanel(root.transform, "Generation / Player Info", new Color(0.14f, 0.10f, 0.08f));
        Anchor((RectTransform)boardRoot.parent.parent, new Vector2(0, 0.25f), new Vector2(0.25f, 0.86f), new Vector2(32, 18), new Vector2(-12, -136));

        controlRoot = CreateScrollablePanel(root.transform, "Cards / Hand / Actions", new Color(0.12f, 0.09f, 0.08f));
        Anchor((RectTransform)controlRoot.parent.parent, new Vector2(0.25f, 0.25f), new Vector2(0.60f, 0.86f), new Vector2(12, 18), new Vector2(-12, -136));

        var rightPanel = CreateBackgroundPanel(root.transform, "Pentagon Location Board", new Color(0.11f, 0.085f, 0.075f));
        Anchor(rightPanel.GetComponent<RectTransform>(), new Vector2(0.60f, 0.25f), new Vector2(1, 0.86f), new Vector2(12, 18), new Vector2(-32, -136));
        rightBoardRoot = rightPanel.transform;

        logRoot = CreateScrollablePanel(root.transform, "Log", new Color(0.10f, 0.08f, 0.07f));
        Anchor((RectTransform)logRoot.parent.parent, new Vector2(0, 0), new Vector2(1, 0.25f), new Vector2(32, 18), new Vector2(-32, -16));
    }

    private void Render()
    {
        Clear(boardRoot);
        Clear(controlRoot);
        Clear(logRoot);
        Clear(rightBoardRoot);
        RenderBoard();
        RenderControls();
        RenderLocationBoard();
        RenderLog();
    }

    private void RenderBoard()
    {
        CreateText(boardRoot, "Phase", $"Generation {game.Generation} — {game.CurrentPhase} — Active: {game.ActivePlayer.Name}\nFirst Player: {game.Players[game.FirstPlayerIndex].Name}\nTurn Order: {game.GetTurnOrderText()}", 28, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));


        foreach (var player in game.Players)
        {
            var buildings = player.Buildings.Count == 0 ? "No buildings" : string.Join(", ", player.Buildings);
            CreateText(
                boardRoot,
                player.Name,
                $"{player.Name} ({player.Character}){(player.Eliminated ? " — ELIMINATED" : string.Empty)}\nCurrent Location: {GetPlayerLocationText(player)}\nClout {player.Clout} | Worker Tokens {player.Workers} | Draw Pile {player.Deck.Count} | Recycle Pile {player.Discard.Count} | Discard Pile {player.Destroyed.Count}\nStored Resources — Alloy {player.Resources.Alloy}, Organics {player.Resources.Organics}, Plastoid {player.Resources.Plastoid}\nTemporary Labor — Labor {player.Resources.Labor}\nBuildings: {buildings}",
                19,
                FontStyle.Normal,
                new Color(0.88f, 0.80f, 0.70f));
        }
    }

    private void RenderControls()
    {
        CreateText(controlRoot, "CenterTitle", "Cards / Hand / Actions", 24, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));
        var activeHand = game.ActivePlayer.Hand.Count == 0 ? "Empty" : string.Join(", ", game.ActivePlayer.Hand);
        CreateText(controlRoot, "CurrentHand", $"{game.ActivePlayer.Name} Hand: {activeHand}", 18, FontStyle.Normal, new Color(0.90f, 0.82f, 0.72f));
        CreateText(controlRoot, "SelectedCardInfo", "Selected Card Info: hover a Recycle, Discard, attack, or build button to see details in the top info banner.", 16, FontStyle.Normal, new Color(0.80f, 0.72f, 0.64f));

        if (inputLocked)
        {
            CreateText(controlRoot, "Input Locked", "Threat movement in progress...", 24, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));
            return;
        }

        if (game.CurrentPhase == Phase.Expedition)
        {
            CreateText(controlRoot, "ExpeditionHint", "Choose workers by clicking Location tiles on the right-side pentagon board.", 18, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));
            CreateButton(controlRoot, "Confirm Expedition", ConfirmExpedition, true, "Confirm Expedition — Send assigned workers to the selected Location and resolve scavenging.");
            CreateButton(controlRoot, "Skip Expedition", SkipExpedition, true, "Skip Expedition — Send 0 worker tokens, choose no Location, and advance to the next player.");
            CreateButton(controlRoot, "Clear Expedition Selection", ClearExpeditionSelection, true, "Clear Expedition Selection — Remove the currently assigned workers and choose again.");
            CreateButton(controlRoot, "Remove 1 Worker", RemoveAssignedWorker, true, "Remove 1 Worker — Reduce the number of workers assigned to this expedition.");
        }
        else if (game.CurrentPhase == Phase.Action)
        {
            CreateButton(controlRoot, "Spend 1 Clout: Gain Worker Token", () =>
            {
                game.SpendCloutForWorkerToken();
                Render();
            }, game.ActivePlayer.Clout > 0, "Spend 1 Clout — Gain 1 worker token for future expeditions. Voluntary spending may reduce your Clout to 0 without eliminating you.");
            CreateButton(controlRoot, "Spend 1 Clout: Buy Worker Card", () =>
            {
                game.SpendCloutForWorkerCard();
                Render();
            }, game.ActivePlayer.Clout > 0, "Spend 1 Clout — Add 1 Worker card to your Recycle Pile. It remains in your deck cycle after reshuffling. Voluntary spending may reduce your Clout to 0 without eliminating you.");

            for (var index = 0; index < game.ActivePlayer.Hand.Count; index++)
            {
                var handIndex = index;
                var card = game.ActivePlayer.Hand[index];
                CreateButton(controlRoot, $"Recycle {card}", () =>
                {
                    game.PlayCard(handIndex, false);
                    Render();
                }, true, $"Recycle {card} — Use the card's recycle effect, then place it in your Recycle Pile. {GetCardTooltip(card)}");
                CreateButton(controlRoot, $"Discard {card}", () =>
                {
                    game.PlayCard(handIndex, true);
                    Render();
                }, true, $"Discard {card} — Use the card's stronger discard effect, then remove it from the game. {GetCardTooltip(card)}");
            }

            if (game.ActivePlayer.Hand.Contains("Soldier"))
            {
                var targets = game.GetSoldierAttackTargets(game.ActivePlayerIndex);
                if (targets.Count == 0)
                {
                    CreateButton(controlRoot, "Attack Player", () => { }, false, "No players at your Location to attack.");
                }
                else
                {
                    foreach (var targetIndex in targets)
                    {
                        var capturedTargetIndex = targetIndex;
                        CreateButton(controlRoot, $"Attack {game.Players[targetIndex].Name} with Soldier", () =>
                        {
                            game.SoldierAttack(game.ActivePlayerIndex, capturedTargetIndex);
                            Render();
                        }, true, $"Attack {game.Players[targetIndex].Name} — Discard Soldier to attack another player at your Location. If undefended, steal 1 random card from their hand if possible and make them lose 1 Clout.");
                    }
                }
            }

            CreateButton(controlRoot, "End Action", () =>
            {
                game.EndActionTurn();
                Render();
            }, true, "End Action — Finish this player's Action Phase turn and continue to the next player or the Junk Storm Phase.");
        }
        else if (game.CurrentPhase == Phase.Storm)
        {
            CreateButton(controlRoot, "Roll Junk Storm Die", () =>
            {
                StartCoroutine(ResolveStormStepwise());
            }, true, "Roll Junk Storm Die — Resolve the generation's hazard roll. 1–5 moves the Junk Storm; 6–10 moves the Biodomers, shown one Location at a time.");
        }
        else if (game.CurrentPhase == Phase.Reset)
        {
            CreateButton(controlRoot, "Reset Generation", () =>
            {
                game.ResetGeneration();
                Render();
            }, true, "Reset Generation — Recycle remaining hands, clear temporary flags, reset temporary Labor, draw back up, check victory, and start the next generation. Stored resources persist. Temporary Labor resets.");
        }
        else
        {
            CreateText(controlRoot, "Winner", $"{game.Winner} wins!", 30, FontStyle.Bold, new Color(0.62f, 0.90f, 0.58f));
        }

        RenderBuildShop();
    }

    private void RenderBuildShop()
    {
        CreateText(controlRoot, "ShopTitle", "Shop / Build", 26, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));
        CreateText(controlRoot, "ShopHint", "All implemented buildings are listed here. Greyed entries explain why they cannot currently be built.", 16, FontStyle.Normal, new Color(0.82f, 0.74f, 0.66f));

        RenderBuildShopTier("Tier 1 Buildings", 1);
        RenderBuildShopTier("Tier 2 Buildings", 2);
        RenderBuildShopTier("Tier 3 Victory Projects", 3);
    }

    private void RenderBuildShopTier(string heading, int tier)
    {
        CreateText(controlRoot, heading, heading, 21, FontStyle.Bold, new Color(0.96f, 0.68f, 0.31f));
        foreach (var building in game.Buildings.Where(candidate => candidate.Tier == tier))
        {
            CreateShopBuildingEntry(building);
        }
    }

    private void CreateShopBuildingEntry(BuildingDefinition building)
    {
        var canBuild = CanBuildFromShop(building);
        var label = GetShopBuildingLabel(building, canBuild);
        var button = CreateButton(controlRoot, label, () =>
        {
            if (!CanBuildFromShop(building))
            {
                SetInfo($"{game.ActivePlayer.Name} cannot build {building.Name}: {GetBuildBlocker(building)}.");
                return;
            }

            game.Build(building.Name);
            Render();
        }, true, GetBuildingTooltip(building, canBuild));

        var image = button.GetComponent<Image>();
        image.color = canBuild ? new Color(1f, 0.72f, 0.30f) : new Color(0.34f, 0.32f, 0.30f);

        var labelText = button.GetComponentInChildren<Text>();
        if (labelText != null)
        {
            labelText.color = canBuild ? new Color(0.12f, 0.08f, 0.06f) : new Color(0.72f, 0.68f, 0.62f);
            labelText.alignment = TextAnchor.MiddleLeft;
        }

        var layout = button.GetComponent<LayoutElement>();
        layout.minHeight = 132;
    }

    private string GetShopBuildingLabel(BuildingDefinition building, bool canBuild)
    {
        var builtMarker = game.ActivePlayer.Buildings.Contains(building.Name) ? " [BUILT]" : string.Empty;
        return $"{building.Name}{builtMarker}\nTier {building.Tier}\nCost: {DescribeCost(building.Cost)}\nRequires: {GetShopRequirementText(building)}\nEffect: {GetBuildingEffectSummary(building)}\nStatus: {(canBuild ? "Can build" : GetBuildBlocker(building))}";
    }

    private bool CanBuildFromShop(BuildingDefinition building)
    {
        return game.CurrentPhase == Phase.Action && game.CanBuild(building);
    }

    private string GetShopRequirementText(BuildingDefinition building)
    {
        var requirements = new List<string>();
        if (!string.IsNullOrWhiteSpace(building.Requires))
        {
            requirements.Add(building.Requires);
        }

        if (building.Tier == 2)
        {
            requirements.Add("any other Tier 1 building");
        }

        if (building.MinClout > 0)
        {
            requirements.Add($"{building.MinClout} Clout");
        }

        return requirements.Count == 0 ? "None" : string.Join(" + ", requirements);
    }

    private string GetBuildingEffectSummary(BuildingDefinition building)
    {
        var cloutText = building.CloutReward > 0 ? $"Gain {building.CloutReward} Clout. " : string.Empty;
        return cloutText + GetBuildingBonusText(building.Name);
    }

    private void RenderLocationBoard()
    {
        CreateText(rightBoardRoot, "BoardTitle", "Location Board", 28, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));
        var titleRect = (RectTransform)rightBoardRoot.Find("BoardTitle");
        Anchor(titleRect, new Vector2(0, 1), new Vector2(1, 1), new Vector2(24, -58), new Vector2(-24, -18));

        CreateText(rightBoardRoot, "BoardHint", "Click pentagon tiles during Expedition to assign workers. Threat markers step here during movement.", 16, FontStyle.Normal, new Color(0.86f, 0.78f, 0.68f));
        var hintRect = (RectTransform)rightBoardRoot.Find("BoardHint");
        Anchor(hintRect, new Vector2(0, 1), new Vector2(1, 1), new Vector2(24, -100), new Vector2(-24, -62));

        for (var index = 0; index < game.Outposts.Count; index++)
        {
            var outpostIndex = index;
            var outpost = game.Outposts[index];
            var button = CreateButton(rightBoardRoot, GetLocationButtonLabel(outpost.Name, outpostIndex), () =>
            {
                AssignExpeditionWorker(outpostIndex);
            }, !inputLocked && game.CurrentPhase == Phase.Expedition, GetExpeditionTooltip(outpost.Name, outpostIndex));
            StyleLocationTile(button, outpostIndex);
            AnchorLocationTile((RectTransform)button.transform, outpostIndex);
        }
    }

    private void RenderLog()
    {
        CreateText(logRoot, "LogTitle", "Event Log", 24, FontStyle.Bold, new Color(1f, 0.81f, 0.46f));
        CreateText(logRoot, "LogEntries", string.Join("\n", game.Log), 18, FontStyle.Normal, new Color(0.86f, 0.78f, 0.68f));
    }


    private void AssignExpeditionWorker(int outpostIndex)
    {
        if (game.CurrentPhase != Phase.Expedition)
        {
            SetInfo("Location tiles assign workers during the Expedition Phase.");
            return;
        }

        if (outpostIndex == DisplayJunkStormOutpost || outpostIndex == DisplayBiodomerOutpost)
        {
            var message = $"{game.ActivePlayer.Name} cannot visit {game.Outposts[outpostIndex].Name}; {GetUnsafeLocationSafetyReason(outpostIndex)}";
            SetInfo(message);
            return;
        }

        var limit = GetExpeditionWorkerLimit();
        if (limit <= 0)
        {
            SetInfo($"{game.ActivePlayer.Name} has no available workers to send. You may still click Skip Expedition.");
            return;
        }

        if (selectedExpeditionOutpost != outpostIndex)
        {
            selectedExpeditionOutpost = outpostIndex;
            assignedExpeditionWorkers = 1;
            SetInfo($"{game.ActivePlayer.Name} changed expedition destination to {game.Outposts[outpostIndex].Name}. Assigned workers reset to 1.");
            Render();
            return;
        }

        if (assignedExpeditionWorkers >= limit)
        {
            SetInfo($"{game.ActivePlayer.Name} cannot send more than {limit} workers.");
            return;
        }

        assignedExpeditionWorkers++;
        SetInfo($"{game.Outposts[outpostIndex].Name} selected. {assignedExpeditionWorkers} workers assigned.");
        Render();
    }

    private void ConfirmExpedition()
    {
        var limit = GetExpeditionWorkerLimit();
        if (selectedExpeditionOutpost < 0 || assignedExpeditionWorkers <= 0)
        {
            SetInfo("Choose a Location and assign at least 1 worker, or click Skip Expedition to send 0 workers.");
            return;
        }

        if (selectedExpeditionOutpost == DisplayJunkStormOutpost || selectedExpeditionOutpost == DisplayBiodomerOutpost)
        {
            SetInfo($"{game.ActivePlayer.Name} cannot visit {game.Outposts[selectedExpeditionOutpost].Name}; {GetUnsafeLocationSafetyReason(selectedExpeditionOutpost)}");
            return;
        }

        if (assignedExpeditionWorkers > limit)
        {
            SetInfo($"{game.ActivePlayer.Name} cannot send more than {limit} workers.");
            return;
        }

        var selectedOutpost = selectedExpeditionOutpost;
        var selectedWorkers = assignedExpeditionWorkers;
        ClearExpeditionSelectionState();
        game.Scavenge(selectedOutpost, selectedWorkers);
        Render();
    }

    private void SkipExpedition()
    {
        ClearExpeditionSelectionState();
        game.SkipExpedition();
        Render();
    }

    private void ClearExpeditionSelection()
    {
        ClearExpeditionSelectionState();
        SetInfo("Expedition selection cleared. Choose a Location and assign workers.");
        Render();
    }

    private void RemoveAssignedWorker()
    {
        if (assignedExpeditionWorkers <= 0)
        {
            ClearExpeditionSelection();
            return;
        }

        assignedExpeditionWorkers--;
        if (assignedExpeditionWorkers == 0)
        {
            selectedExpeditionOutpost = -1;
        }

        SetInfo("Removed 1 worker from the expedition selection.");
        Render();
    }

    private void ClearExpeditionSelectionState()
    {
        selectedExpeditionOutpost = -1;
        assignedExpeditionWorkers = 0;
    }

    private int GetExpeditionWorkerLimit()
    {
        return Mathf.Min(game.ActivePlayer.Clout, game.ActivePlayer.Workers);
    }

    private IEnumerator ResolveStormStepwise()
    {
        inputLocked = true;
        var roll = Random.Range(1, 11);
        var movingStorm = roll <= 5;
        var direction = roll % 2 == 0 ? 1 : -1;
        var distance = movingStorm ? roll : roll - 5;
        var directionName = direction > 0 ? "clockwise" : "counterclockwise";
        var arrow = direction > 0 ? "→" : "←";
        var current = movingStorm ? game.JunkStormOutpost : game.BiodomerOutpost;
        var threatName = movingStorm ? "Junk Storm" : "Biodomers";

        Render();
        SetInfo($"{threatName} rolled {roll}. Moving {directionName}...");
        yield return new WaitForSeconds(0.45f);

        for (var step = 0; step < distance; step++)
        {
            var previous = current;
            current = WrapLocation(current + direction);
            if (movingStorm)
            {
                displayedJunkStormOutpost = current;
            }
            else
            {
                displayedBiodomerOutpost = current;
            }

            Render();
            SetInfo($"{threatName} moving {directionName}: {game.Outposts[previous].Name} {arrow} {game.Outposts[current].Name}");
            yield return new WaitForSeconds(0.55f);
        }

        displayedJunkStormOutpost = null;
        displayedBiodomerOutpost = null;
        game.ResolveStormRoll(roll);
        inputLocked = false;
        Render();
    }

    private int WrapLocation(int index)
    {
        return (index + game.Outposts.Count) % game.Outposts.Count;
    }

    private void ShowRulebook()
    {
        if (rulebookOverlay == null)
        {
            return;
        }

        rulebookOverlay.SetActive(true);
        rulebookOverlay.transform.SetAsLastSibling();
        ShowRulebookSection(0);
        SetInfo("Rulebook — Review the indexed rules reference.");
    }

    private void CloseRulebook()
    {
        if (rulebookOverlay != null)
        {
            rulebookOverlay.SetActive(false);
        }

        ClearInfo();
    }

    private void ShowRulebookSection(int sectionIndex)
    {
        if (rulebookContentText == null || sectionIndex < 0 || sectionIndex >= RulebookSections.Length)
        {
            return;
        }

        var section = RulebookSections[sectionIndex];
        rulebookContentText.text = $"{sectionIndex + 1}. {section.Title}\n\n{section.Content}";
    }

    public void SetInfo(string message)
    {
        if (infoBannerText != null)
        {
            infoBannerText.text = string.IsNullOrWhiteSpace(message) ? DefaultInfoText : message;
        }
    }

    public void ClearInfo()
    {
        SetInfo(DefaultInfoText);
    }

    private string GetCardTooltip(string cardName)
    {
        if (cardName == "Worker")
        {
            return "Worker — Starter. Recycle: Gain 1 temporary Labor this generation. Discard: Gain 2 temporary Labor this generation. Labor is used to build and resets at the end of the generation.";
        }

        if (!game.Cards.TryGetValue(cardName, out var card))
        {
            return cardName;
        }

        var notes = cardName switch
        {
            "Storm Shield" => "Timing: discard from hand to cancel all Junk Storm effects against you this generation.",
            "Soldier" => "Discard: cancel a Biodomer attack, attack another player at your Location, or defend against a Soldier attack at your Location.",
            "Weapon Outfitting" => "Timing: discard from hand to cancel one Biodomer attack against you.",
            "Preemptive Intelligence" => "Timing: recycle to cancel one Attack card targeting you.",
            _ => string.Empty
        };

        return $"{card.Name} — {card.Type}. Recycle: {DescribeEffect(card.Recycle)} Discard: {DescribeEffect(card.Destroy)} {notes}".Trim();
    }

    private string GetBuildingTooltip(BuildingDefinition building, bool canBuild)
    {
        var requirement = string.IsNullOrWhiteSpace(building.Requires) ? "None" : building.Requires;
        var bonus = building.CloutReward > 0 ? $"Gain {building.CloutReward} Clout when built." : "Completes a Tier 3 victory project.";
        var expeditionBonus = GetBuildingBonusText(building.Name);
        var status = canBuild ? "Currently: can build." : $"Currently unavailable: {GetBuildBlocker(building)}";
        return $"{building.Name} — Tier {building.Tier}. Cost: {DescribeCost(building.Cost)}. Requirement: {requirement}. {bonus} {expeditionBonus} {status}";
    }

    private string GetExpeditionTooltip(string locationName, int outpostIndex)
    {
        if (outpostIndex == DisplayJunkStormOutpost || outpostIndex == DisplayBiodomerOutpost)
        {
            return $"{locationName} — Cards: {game.Outposts[outpostIndex].Deck.Count}. Unsafe. {GetUnsafeLocationSafetyReason(outpostIndex)} Players cannot choose this Location this generation.";
        }

        if (selectedExpeditionOutpost == outpostIndex && assignedExpeditionWorkers > 0)
        {
            return $"{locationName} — Selected for expedition. {assignedExpeditionWorkers} workers assigned. Click again to assign 1 more worker.";
        }

        return $"{locationName} — Cards: {game.Outposts[outpostIndex].Deck.Count}. Click to assign 1 worker. Click again to assign another worker. Confirm Expedition when ready, or Skip Expedition to send 0 workers.";
    }

    private string GetUnsafeLocationSafetyReason(int outpostIndex)
    {
        var junkStormHere = DisplayJunkStormOutpost == outpostIndex;
        var biodomersHere = DisplayBiodomerOutpost == outpostIndex;
        if (junkStormHere && biodomersHere)
        {
            return "The Junk Storm and Biodomers are here.";
        }

        if (junkStormHere)
        {
            return "The Junk Storm is here.";
        }

        if (biodomersHere)
        {
            return "The Biodomers are here.";
        }

        return "Safe to visit this generation.";
    }

    private string GetLocationButtonLabel(string locationName, int outpostIndex)
    {
        var lines = new List<string> { $"⬟ {locationName}", $"Cards: {game.Outposts[outpostIndex].Deck.Count}" };
        var markerText = GetThreatMarkerText(outpostIndex);
        if (!string.IsNullOrWhiteSpace(markerText))
        {
            lines.Add(markerText);
            lines.Add("Unsafe");
        }

        if (selectedExpeditionOutpost == outpostIndex && assignedExpeditionWorkers > 0)
        {
            lines.Add($"Selected: {assignedExpeditionWorkers} workers");
        }

        return string.Join("\n", lines);
    }

    private string GetThreatMarkerText(int outpostIndex)
    {
        var markers = new List<string>();
        if (DisplayJunkStormOutpost == outpostIndex)
        {
            markers.Add("[JUNK STORM]");
        }

        if (DisplayBiodomerOutpost == outpostIndex)
        {
            markers.Add("[BIODOMERS]");
        }

        return string.Join("\n", markers);
    }

    private string GetLocationSafetyText(int outpostIndex)
    {
        var junkStormHere = DisplayJunkStormOutpost == outpostIndex;
        var biodomersHere = DisplayBiodomerOutpost == outpostIndex;
        if (junkStormHere && biodomersHere)
        {
            return "Currently unsafe: Junk Storm and Biodomers are here.";
        }

        if (junkStormHere)
        {
            return "Currently unsafe: Junk Storm is here.";
        }

        if (biodomersHere)
        {
            return "Currently unsafe: Biodomers are here.";
        }

        return "Safe to visit this generation.";
    }

    private string GetPlayerLocationText(PlayerState player)
    {
        if (player.ExpeditionOutpost < 0 || player.ExpeditionOutpost >= game.Outposts.Count)
        {
            return "Colony";
        }

        return $"{game.Outposts[player.ExpeditionOutpost].Name} ({player.ExpeditionWorkers} worker(s))";
    }

    private int DisplayJunkStormOutpost => displayedJunkStormOutpost ?? game.JunkStormOutpost;

    private int DisplayBiodomerOutpost => displayedBiodomerOutpost ?? game.BiodomerOutpost;

    private string GetBuildBlocker(BuildingDefinition building)
    {
        if (game.CurrentPhase != Phase.Action)
        {
            return "building is only available during the Action Phase";
        }

        if (game.ActivePlayer.Buildings.Contains(building.Name))
        {
            return "already built";
        }

        if (building.MinClout > 0 && game.ActivePlayer.Clout < building.MinClout)
        {
            return $"requires {building.MinClout} Clout";
        }

        if (!string.IsNullOrWhiteSpace(building.Requires) && !game.ActivePlayer.Buildings.Contains(building.Requires))
        {
            return $"requires {building.Requires}";
        }

        if (building.Tier == 2 && game.ActivePlayer.Buildings.Count < 2)
        {
            return "requires two Tier 1 buildings";
        }

        return GetResourceShortfallText(building.Cost);
    }

    private string GetResourceShortfallText(ResourcePool cost)
    {
        var resources = game.ActivePlayer.Resources;
        var missing = new List<string>();
        if (resources.Organics < cost.Organics)
        {
            missing.Add($"needs {cost.Organics - resources.Organics} more Organics");
        }

        if (resources.Alloy < cost.Alloy)
        {
            missing.Add($"needs {cost.Alloy - resources.Alloy} more Alloy");
        }

        if (resources.Plastoid < cost.Plastoid)
        {
            missing.Add($"needs {cost.Plastoid - resources.Plastoid} more Plastoid");
        }

        if (resources.Labor < cost.Labor)
        {
            missing.Add($"needs {cost.Labor - resources.Labor} more Labor");
        }

        var remainingAlloy = Mathf.Max(0, resources.Alloy - cost.Alloy);
        var remainingPlastoid = Mathf.Max(0, resources.Plastoid - cost.Plastoid);
        var flexibleShortfall = cost.FlexibleAlloyPlastoid - remainingAlloy - remainingPlastoid;
        if (flexibleShortfall > 0)
        {
            missing.Add($"needs {flexibleShortfall} more Alloy/Plastoid");
        }

        return missing.Count == 0 ? "cannot afford the stored resource or temporary Labor cost" : string.Join(", ", missing);
    }

    private static string GetBuildingBonusText(string buildingName)
    {
        return buildingName switch
        {
            "Farm" => "Expedition Bonus: scavenged Organics may go on top of your Draw Pile.",
            "Military Base" => "Expedition Bonus: lose 1 fewer worker if Biodomers attack and you cannot defend.",
            "Laboratory" => "Expedition Bonus: discard 1 fewer Draw Pile card if the Junk Storm affects you and you cannot defend.",
            "Transportation Station" => "Expedition Bonus: scavenged Alloy or Plastoid may go on top of your Draw Pile.",
            "Farming Center" => "Colony Bonus: each player gains 1 worker token. Expedition Bonus: scavenge 1 additional card per worker.",
            "Weapons Factory" => "Colony Bonus: each player adds a Weapon Outfitting card to their Recycle Pile. Expedition Bonus: unaffected by Biodomers this generation.",
            "Internet Servers" => "Colony Bonus: once per generation, each player may reduce a building cost by 1 Alloy or Plastoid. Expedition Bonus: unaffected by the Junk Storm this generation.",
            "Subway Station" => "Colony Bonus: each player may bring 1 additional worker token on expeditions. Expedition Bonus: scavenged cards may go on top of your Draw Pile.",
            "Terraforming Station" => "Victory Meaning: terraform the planet and make Earth livable again.",
            "Rocket Launch Pad" => "Victory Meaning: escape Earth and build humanity's future elsewhere.",
            "Deep Earth Drill" => "Victory Meaning: tunnel beneath the ruined world and create a hidden civilization.",
            "Advanced Communications Array" => "Victory Meaning: hack the nanosphere and take control of the Junk Storm.",
            _ => string.Empty
        };
    }

    private static string DescribeEffect(Effect effect)
    {
        var parts = new System.Collections.Generic.List<string>();
        if (effect.Clout != 0) parts.Add($"Gain {effect.Clout} Clout");
        if (effect.Workers != 0) parts.Add($"Gain {effect.Workers} worker(s)");
        if (effect.Alloy != 0) parts.Add($"Generate {effect.Alloy} Alloy");
        if (effect.Organics != 0) parts.Add($"Generate {effect.Organics} Organics");
        if (effect.Plastoid != 0) parts.Add($"Generate {effect.Plastoid} Plastoid");
        if (effect.Labor != 0) parts.Add($"Gain {effect.Labor} temporary Labor this generation");
        if (effect.Defense != 0) parts.Add($"Gain {effect.Defense} Defense Strength this generation");
        if (effect.Draw != 0) parts.Add($"Draw {effect.Draw} card(s)");
        if (effect.TargetCloutLoss != 0) parts.Add($"Target loses {effect.TargetCloutLoss} Clout");
        if (effect.TargetWorkerLoss != 0) parts.Add($"Target loses {effect.TargetWorkerLoss} worker(s)");
        if (effect.StormShield) parts.Add("Cancel all Junk Storm effects against you this generation");
        if (effect.BiodomeShield) parts.Add("Cancel one Biodomer attack against you");
        return parts.Count == 0 ? "No effect." : string.Join(", ", parts) + ".";
    }

    private static string DescribeCost(ResourcePool cost)
    {
        var parts = new System.Collections.Generic.List<string>();
        if (cost.Organics > 0) parts.Add($"{cost.Organics} Organics");
        if (cost.Alloy > 0) parts.Add($"{cost.Alloy} Alloy");
        if (cost.Plastoid > 0) parts.Add($"{cost.Plastoid} Plastoid");
        if (cost.FlexibleAlloyPlastoid > 0) parts.Add($"{cost.FlexibleAlloyPlastoid} Alloy/Plastoid");
        if (cost.Labor > 0) parts.Add($"{cost.Labor} Labor");
        return parts.Count == 0 ? "Free" : string.Join(" + ", parts);
    }

    private static void EnsureEventSystem()
    {
        if (EventSystem.current != null)
        {
            return;
        }

        var eventSystem = new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));
        DontDestroyOnLoad(eventSystem);
    }

    private void AnchorLocationTile(RectTransform rectTransform, int outpostIndex)
    {
        // Canonical movement ring order: City Ruins → Suburbs → Research Facility → Military Base → Farmlands.
        var positions = new[]
        {
            new Vector2(0.50f, 0.78f),
            new Vector2(0.82f, 0.58f),
            new Vector2(0.70f, 0.25f),
            new Vector2(0.30f, 0.25f),
            new Vector2(0.18f, 0.58f)
        };

        var position = positions[outpostIndex];
        rectTransform.anchorMin = position;
        rectTransform.anchorMax = position;
        rectTransform.pivot = new Vector2(0.5f, 0.5f);
        rectTransform.sizeDelta = new Vector2(190, 122);
        rectTransform.anchoredPosition = Vector2.zero;
    }

    private void StyleLocationTile(Button button, int outpostIndex)
    {
        var image = button.GetComponent<Image>();
        image.color = outpostIndex == DisplayJunkStormOutpost || outpostIndex == DisplayBiodomerOutpost
            ? new Color(0.52f, 0.22f, 0.14f)
            : new Color(0.98f, 0.67f, 0.25f);

        var layout = button.GetComponent<LayoutElement>();
        layout.ignoreLayout = true;
        layout.minHeight = 112;
        layout.minWidth = 180;

        var outline = button.gameObject.AddComponent<Outline>();
        outline.effectColor = new Color(0.08f, 0.04f, 0.02f, 0.95f);
        outline.effectDistance = new Vector2(3, -3);
    }

    private Button CreateButton(Transform parent, string label, UnityEngine.Events.UnityAction onClick, bool interactable = true, string tooltipText = null)
    {
        var buttonObject = new GameObject(label, typeof(RectTransform), typeof(Image), typeof(Button), typeof(LayoutElement));
        buttonObject.transform.SetParent(parent, false);
        buttonObject.GetComponent<Image>().color = interactable ? new Color(1f, 0.72f, 0.30f) : new Color(0.35f, 0.31f, 0.28f);

        var button = buttonObject.GetComponent<Button>();
        button.interactable = interactable;
        button.onClick.AddListener(onClick);

        var layout = buttonObject.GetComponent<LayoutElement>();
        layout.minHeight = 46;
        layout.minWidth = 118;

        var text = CreateText(buttonObject.transform, "Label", label, 17, FontStyle.Bold, new Color(0.12f, 0.08f, 0.06f));
        Stretch(text.rectTransform, 8, -4, -8, 4);
        text.alignment = TextAnchor.MiddleCenter;
        AddTooltip(buttonObject, tooltipText ?? label);
        return button;
    }

    private void AddTooltip(GameObject target, string tooltipText)
    {
        var trigger = target.AddComponent<TooltipTrigger>();
        trigger.Initialize(this, tooltipText);
    }

    private Text CreateText(Transform parent, string name, string value, int size, FontStyle style, Color color)
    {
        var textObject = new GameObject(name, typeof(RectTransform), typeof(Text), typeof(LayoutElement));
        textObject.transform.SetParent(parent, false);
        var text = textObject.GetComponent<Text>();
        text.text = value;
        text.font = uiFont != null ? uiFont : Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        text.fontSize = size;
        text.fontStyle = style;
        text.color = color;
        text.alignment = TextAnchor.UpperLeft;
        text.horizontalOverflow = HorizontalWrapMode.Wrap;
        text.verticalOverflow = VerticalWrapMode.Overflow;

        var layout = textObject.GetComponent<LayoutElement>();
        layout.minHeight = Mathf.Max(36, value.Split('\n').Length * (size + 8));
        return text;
    }

    private void BuildRulebookOverlay(Transform parent)
    {
        rulebookOverlay = CreateBackgroundPanel(parent, "Rulebook Overlay", new Color(0f, 0f, 0f, 0.74f));
        Stretch(rulebookOverlay.GetComponent<RectTransform>());

        var modal = CreateBackgroundPanel(rulebookOverlay.transform, "Rulebook Modal", new Color(0.10f, 0.075f, 0.06f, 0.98f));
        Anchor(modal.GetComponent<RectTransform>(), new Vector2(0.06f, 0.07f), new Vector2(0.94f, 0.92f), Vector2.zero, Vector2.zero);

        var title = CreateText(modal.transform, "Rulebook Title", "Junk Storm Rulebook", 34, FontStyle.Bold, Color.white);
        Anchor(title.rectTransform, new Vector2(0, 1), new Vector2(1, 1), new Vector2(24, -70), new Vector2(-180, -18));

        CreateButton(modal.transform, "Close", CloseRulebook, true, "Close — Return to the game.");
        var closeRect = (RectTransform)modal.transform.Find("Close");
        Anchor(closeRect, new Vector2(1, 1), new Vector2(1, 1), new Vector2(-154, -66), new Vector2(-24, -20));

        var indexRoot = CreateScrollablePanel(modal.transform, "Rulebook Index", new Color(0.14f, 0.10f, 0.08f));
        Anchor((RectTransform)indexRoot.parent.parent, new Vector2(0, 0), new Vector2(0.30f, 1), new Vector2(24, 24), new Vector2(-10, -88));

        var contentRoot = CreateScrollablePanel(modal.transform, "Rulebook Content", new Color(0.13f, 0.095f, 0.08f));
        Anchor((RectTransform)contentRoot.parent.parent, new Vector2(0.30f, 0), new Vector2(1, 1), new Vector2(10, 24), new Vector2(-24, -88));

        for (var index = 0; index < RulebookSections.Length; index++)
        {
            var sectionIndex = index;
            var section = RulebookSections[index];
            CreateButton(indexRoot, $"{index + 1}. {section.Title}", () => ShowRulebookSection(sectionIndex), true, $"Open the {section.Title} rules section.");
        }

        rulebookContentText = CreateText(contentRoot, "Rulebook Section Text", string.Empty, 20, FontStyle.Normal, new Color(0.92f, 0.84f, 0.72f));
        ShowRulebookSection(0);
        rulebookOverlay.SetActive(false);
    }

    private GameObject CreateUtilityPanel(Transform parent)
    {
        var panel = new GameObject("Utility Buttons", typeof(RectTransform), typeof(Image), typeof(HorizontalLayoutGroup));
        panel.transform.SetParent(parent, false);
        panel.GetComponent<Image>().color = new Color(0.11f, 0.075f, 0.055f, 0.95f);

        var layout = panel.GetComponent<HorizontalLayoutGroup>();
        layout.padding = new RectOffset(8, 8, 6, 6);
        layout.spacing = 8;
        layout.childAlignment = TextAnchor.MiddleRight;
        layout.childControlWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandWidth = false;
        layout.childForceExpandHeight = true;
        return panel;
    }

    private Transform CreateScrollablePanel(Transform parent, string name, Color color)
    {
        var panel = CreateBackgroundPanel(parent, name, color);
        var scrollRect = panel.AddComponent<ScrollRect>();
        scrollRect.horizontal = false;
        scrollRect.vertical = true;
        scrollRect.movementType = ScrollRect.MovementType.Clamped;
        scrollRect.scrollSensitivity = 28f;

        var viewport = new GameObject("Viewport", typeof(RectTransform), typeof(RectMask2D), typeof(Image));
        viewport.transform.SetParent(panel.transform, false);
        viewport.GetComponent<Image>().color = new Color(1f, 1f, 1f, 0.01f);
        Stretch(viewport.GetComponent<RectTransform>(), 18, -18, -18, 18);

        var content = new GameObject("Content", typeof(RectTransform), typeof(VerticalLayoutGroup), typeof(ContentSizeFitter));
        content.transform.SetParent(viewport.transform, false);

        var contentRect = content.GetComponent<RectTransform>();
        contentRect.anchorMin = new Vector2(0, 1);
        contentRect.anchorMax = new Vector2(1, 1);
        contentRect.pivot = new Vector2(0.5f, 1);
        contentRect.offsetMin = Vector2.zero;
        contentRect.offsetMax = Vector2.zero;

        var layout = content.GetComponent<VerticalLayoutGroup>();
        layout.spacing = 10;
        layout.childAlignment = TextAnchor.UpperLeft;
        layout.childControlWidth = true;
        layout.childControlHeight = true;
        layout.childForceExpandWidth = true;
        layout.childForceExpandHeight = false;

        var fitter = content.GetComponent<ContentSizeFitter>();
        fitter.horizontalFit = ContentSizeFitter.FitMode.Unconstrained;
        fitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;

        scrollRect.viewport = viewport.GetComponent<RectTransform>();
        scrollRect.content = contentRect;
        return content.transform;
    }

    private GameObject CreateBackgroundPanel(Transform parent, string name, Color color)
    {
        var panel = new GameObject(name, typeof(RectTransform), typeof(Image));
        panel.transform.SetParent(parent, false);
        panel.GetComponent<Image>().color = color;
        return panel;
    }

    private static void Clear(Transform root)
    {
        for (var i = root.childCount - 1; i >= 0; i--)
        {
            Destroy(root.GetChild(i).gameObject);
        }
    }

    private static void Stretch(RectTransform rectTransform, float left = 0, float top = 0, float right = 0, float bottom = 0)
    {
        rectTransform.anchorMin = Vector2.zero;
        rectTransform.anchorMax = Vector2.one;
        rectTransform.offsetMin = new Vector2(left, bottom);
        rectTransform.offsetMax = new Vector2(right, top);
    }

    private static void Anchor(RectTransform rectTransform, Vector2 min, Vector2 max, Vector2 offsetMin, Vector2 offsetMax)
    {
        rectTransform.anchorMin = min;
        rectTransform.anchorMax = max;
        rectTransform.offsetMin = offsetMin;
        rectTransform.offsetMax = offsetMax;
    }
}

public sealed class TooltipTrigger : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler
{
    private JunkStormUnityController owner;
    private string message;

    public void Initialize(JunkStormUnityController tooltipOwner, string tooltipMessage)
    {
        owner = tooltipOwner;
        message = tooltipMessage;
    }

    public void OnPointerEnter(PointerEventData eventData)
    {
        owner?.SetInfo(message);
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        owner?.ClearInfo();
    }
}
